INHERIT:
  - configs/paths.yaml
  - configs/augment.yaml
  - configs/data.yaml
  - configs/model.yaml

seed: 42
num_workers: 0 #8
fold_idx: 0
num_folds: 5
num_epochs: 32
batch_size: 256
train_pct: 0.8
lr:
  initial: 0.003
  warmup_factor: 10
  warmup_epoch: 1
  weight_decay: 0.001

loss_func:
  module: torch.nn
  function: CrossEntropyLoss # BCEWithLogitsLoss

optimizer:
  module: torch.optim # kaggen.train.optimizers
  name: SGD # Over9000

scheduler:
  module: torch.optim.lr_scheduler
  name: CosineAnnealingLR

performance_metric_name: accuracy
metrics:
  accuracy:
    module: kaggen.train.metrics
    name: accuracy
    parameters:

train_data:
  module: torchvision.datasets
  func_name: CIFAR10
  parameters:
    root: "./data"
    train: True
    download: True

valid_data:
  module: torchvision.datasets
  func_name: CIFAR10
  parameters:
    root: "./data"
    train: False
    download: True
